INSERT INTO commune (name)
VALUES
('Algarrobo'),
('Alhué'),
('Alto Biobío'),
('Alto del Carmen'),
('Ancud'),
('Andacollo'),
('Angol'),
('Antofagasta'),
('Antuco'),
('Arauco'),
('Arica'),
('Aysén'),
('Buin'),
('Cabildo'),
('Calama'),
('Calbuco'),
('Caldera'),
('Calle Larga'),
('Camarones'),
('Camiña'),
('Canela'),
('Cañete'),
('Cartagena'),
('Casablanca'),
('Castro'),
('Catemu'),
('Cauquenes'),
('Cerrillos'),
('Cerro Navia'),
('Chaitén'),
('Chile Chico'),
('Chillán'),
('Chillán Viejo'),
('Colina'),
('Concepción'),
('Concón'),
('Conchalí'),
('Copiapó'),
('Coquimbo'),
('Coronel'),
('Curacaví'),
('Curicó'),
('El Bosque'),
('El Quisco'),
('El Tabo'),
('Estación Central'),
('Florida'),
('Frutillar'),
('Hualpén'),
('Huechuraba'),
('Independencia'),
('Iquique'),
('La Cisterna'),
('La Florida'),
('La Granja'),
('La Pintana'),
('La Reina'),
('Las Condes'),
('Limache'),
('Linares'),
('Lo Barnechea'),
('Lo Espejo'),
('Lo Prado'),
('Los Andes'),
('Los Ángeles'),
('Machalí'),
('Maipú'),
('Melipilla'),
('Ñuñoa'),
('Osorno'),
('Ovalle'),
('Padre Hurtado'),
('Paine'),
('Peñaflor'),
('Peñalolén'),
('Providencia'),
('Pudahuel'),
('Puente Alto'),
('Puerto Montt'),
('Puerto Varas'),
('Punta Arenas'),
('Quilicura'),
('Quillota'),
('Quilpué'),
('Quinta Normal'),
('Recoleta'),
('Renca'),
('Rengo'),
('Rancagua'),
('San Antonio'),
('San Bernardo'),
('San Felipe'),
('San Fernando'),
('San Joaquín'),
('San Miguel'),
('San Ramón'),
('Santiago'),
('Talagante'),
('Talca'),
('Temuco'),
('Tocopilla'),
('Valdivia'),
('Valparaíso'),
('Villa Alemana'),
('Viña del Mar'),
('Vitacura');

INSERT INTO entity (
    rut,
    type,
    first_name,
    last_name_father,
    last_name_mother,
    address,
    commune_id,
    email,
    phone
)
VALUES (
    '12345678-9',
    'person',
    'Pedro',
    'Ruiz',
    'Perez',
    'Av. Example 123',
    (SELECT id FROM commune WHERE name = 'La Florida'),
    'pedro@test.com',
    '987654321'
);

INSERT INTO entity (
    rut,
    type,
    business_name,
    address,
    commune_id,
    email,
    phone
)
VALUES (
    '76.123.456-7',
    'company',
    'Transportes Fernández SpA',
    'Av. Industrial 456',
    (SELECT id FROM commune WHERE name = 'Santiago'),
    'contacto@transportes.cl',
    '912345678'
);